### ISSUE TITLE
Security Error encountered on initial Twitter page load (BLOCKED)

### ISSUE THREAD

**Issue by izzydoescode** [tiansh/block-twitter-promoted#1]
Error from your extension on `https://twitter.com` doesn't allow page to load. Errors encountered in the console: 
```
Security Error: Content at https://twitter.com/ may not load or link to moz-extension://5dcb94c7-dee7-d649-8f15-509274c1baf2/page.js.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

 Pls see pic below:

![image](https://user-images.githubusercontent.com/15269860/81811367-873ade00-94f2-11ea-888f-863ea7bcb850.png)

Seems like either Twitter or most likely Mozilla doesn't like you messing with their page loads!

**Comment by tiansh** [comment]
So, will Twitter be normally load after this message? Will any functions in this extension break? What's wrong beside this annoying message?

**Comment by tiansh** [comment]
I will release a small update to get ride of the annoying message. But this extension currently works for me. I'm not sure what's wrong on your browser. Could you tell me more about your environment (browser versions), and details about what's going wrong? If this still happened, also try to disable other extensions to make sure this happened due to this one.

**Comment by tiansh** [comment]
Version 0.1.6 had listed on AMO. The error message should be suspended in 0.1.6.
